version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
    volumes:
      - ./client:/app
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment: 
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/userTrackingDB
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
